### ISSUE TITLE
Real CVD data as an option for trend

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#4]
We discussed using the Chicago CVD data as an option for the trend parameter, but I haven't yet figured out how to make that work.  It would go in the calc_t function.

**Comment by geanders** [comment]
We could do this as an alternative to `calc_t`, through a customized function, rather than put it in `calc_t`, maybe. I put in one function (`custom_baseline`) that pulls real mortality data from the Chicago dataset and then smooths it and outputs a mean daily value from that smoothed real data, and then later functions can add the random Poisson noise to it. We might be able to start from the `custom_baseline` code, and tweak that to work like we want (for example, I think that now it only pulls starting from the first day in the Chicago time series, so it always starts with days in the winter-- we might want to change that).
